// apps/web-vue/src/components/shared/ErrorCard.vue
<script setup lang="ts">
import IconError from '../icons/IconError.vue'
import { splitByNewline } from '@imdaesomun/shared/utils/format-util'

const props = defineProps<{
  content?: string
}>()
</script>

<template>
  <div class="flex flex-col items-center gap-2 rounded-xl bg-white p-4 shadow-sm">
    <IconError class="w-8 flex-shrink-0 text-red-400" />
    <div class="text-center">
      <p
        v-for="(line, index) in splitByNewline(
          props.content ?? '오류가 발생했어요\n잠시 후 다시 시도해주세요',
        )"
        :key="index"
        class="text-body text-gray-500"
      >
        {{ line }}
      </p>
    </div>
  </div>
</template>

// apps/web-next/src/components/shared/ErrorCard.tsx
import { IconError } from '../icons/IconError';
import { splitByNewline } from '@imdaesomun/shared/utils/format-util';

type ErrorCardProps = {
  content?: string;
};

export const ErrorCard = ({ content }: ErrorCardProps) => {
  const lines = splitByNewline(
    content ?? '오류가 발생했어요\n잠시 후 다시 시도해주세요'
  );

  return (
    <div className="flex flex-col items-center gap-2 rounded-xl bg-white p-4 shadow-sm">
      <IconError className="w-8 flex-shrink-0 text-red-400" />
      <div className="text-center">
        {lines.map((line, index) => (
          <p key={index} className="text-body text-gray-500">
            {line}
          </p>
        ))}
      </div>
    </div>
  );
};
