// apps/web-vue/src/layouts/AppModalLayout.vue
<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 z-40 flex items-center justify-center"
  >
    <div class="absolute inset-0 bg-black opacity-50" @click="close" />
    <div class="z-1 mx-4 w-full max-w-sm rounded-xl bg-gray-50 p-4 shadow-xl">
      <component :is="modalComponent" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useModal } from '@/composables/useModal';

const { isOpen, close, modalComponent } = useModal();
</script>

// apps/web-next/src/components/layouts/AppModalLayout.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

interface AppModalLayoutProps {
  children: React.ReactNode;
}

export const AppModalLayout = ({ children }: AppModalLayoutProps) => {
  const router = useRouter();

  useEffect(() => {
    document.body.classList.add('no-scroll');
    return () => {
      document.body.classList.remove('no-scroll');
    };
  }, []);

  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center">
      <div
        className="absolute inset-0 bg-black opacity-50"
        onClick={() => router.back()}
      />
      <div className="z-1 mx-4 w-full max-w-sm rounded-xl bg-gray-50 p-4 shadow-xl">
        {children}
      </div>
    </div>
  );
};
