// apps/web-vue/src/components/ui/AppAvatar.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import IconProfile from '../icons/IconProfile.vue';

const props = defineProps<{
  photoURL?: string | null;
  isLogin: boolean;
}>();

const hasError = ref(false);

const onImageError = () => {
  hasError.value = true;
};

const containerClass = computed(() => {
  return {
    'bg-teal-500-10': props.isLogin,
    'bg-gray-500-10': !props.isLogin,
  };
});

const avatarClass = computed(() => {
  return {
    'text-teal-500': props.isLogin,
    'text-gray-400': !props.isLogin,
  };
});
</script>

<template>
  <div
    class="flex items-center justify-center overflow-hidden rounded-full"
    :class="containerClass"
  >
    <img
      v-if="props.photoURL && !hasError"
      :src="props.photoURL"
      alt="User Avatar"
      class="block w-full"
      loading="lazy"
      @error="onImageError"
    />
    <IconProfile
      v-if="!props.photoURL || hasError"
      class="w-4/5"
      :class="avatarClass"
    />
  </div>
</template>

// apps/web-next/src/components/ui/AppAvatar.tsx
'use client';

import React, { useState } from 'react';
import Image from 'next/image';
import IconProfile from '../icons/IconProfile';

type AppAvatarProps = {
  photoURL?: string | null;
  isLogin: boolean;
  className?: string | null;
};

const AppAvatar: React.FC<AppAvatarProps> = ({
  photoURL,
  isLogin,
  className,
}) => {
  const [hasError, setHasError] = useState(false);

  const onImageError = () => {
    setHasError(true);
  };

  const containerClass = isLogin ? 'bg-teal-500-10' : 'bg-gray-500-10';

  const avatarClass = isLogin ? 'text-teal-500' : 'text-gray-400';

  return (
    <div
      className={`flex items-center justify-center overflow-hidden rounded-full ${containerClass} ${className}`}
    >
      {photoURL && !hasError ? (
        <Image
          src={photoURL}
          alt="User Avatar"
          onError={onImageError}
          width={24}
          height={24}
        />
      ) : (
        <IconProfile className={`w-4/5 ${avatarClass}`} />
      )}
    </div>
  );
};

export default AppAvatar;
