// apps/web-next/src/components/saved/SavedFilter.tsx
'use client';

import { useSavedFilterStore } from '@/stores/filter.store';
import { useEffect, useRef, useState } from 'react';
import { AppRadioButton } from '../ui/AppRadioButton';

interface SavedFilterProps {
  totalCount: number;
  shCount: number;
  ghCount: number;
  ihCount: number;
  bmcCount: number;
}

export const SavedFilter = ({
  totalCount,
  shCount,
  ghCount,
  ihCount,
  bmcCount,
}: SavedFilterProps) => {
  const savedFilter = useSavedFilterStore((state) => state.savedFilter);
  const setSavedFilter = useSavedFilterStore((state) => state.setSavedFilter);

  const [isStuck, setIsStuck] = useState(false);
  const filterContainerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsStuck(false);
        } else {
          setIsStuck(true);
        }
      },
      {
        rootMargin: '-1px 0px 0px 0px',
        threshold: 1,
      }
    );

    const currentRef = filterContainerRef.current;
    if (currentRef) {
      observer.observe(currentRef);
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef);
      }
    };
  }, []);

  const corporationFilterList = [
    { label: '전체', value: null, count: totalCount },
    { label: 'SH', value: 'sh', count: shCount },
    { label: 'GH', value: 'gh', count: ghCount },
    { label: 'IH', value: 'ih', count: ihCount },
    { label: 'BMC', value: 'bmc', count: bmcCount },
  ];

  const handleFilterChange = (value: string | null) => {
    setSavedFilter(value);
  };

  const stickyClass = isStuck
    ? 'bg-white shadow-sm md:shadow-none md:bg-transparent'
    : 'bg-transparent';

  return (
    <div
      ref={filterContainerRef}
      className={`sticky top-0 z-10 flex gap-2 overflow-x-auto px-4 py-2 transition-all md:relative ${stickyClass}`}
    >
      {corporationFilterList.map((filter) => (
        <AppRadioButton
          key={filter.label}
          label={filter.label}
          count={filter.count}
          value={filter.value}
          groupValue={savedFilter}
          onChangeAction={handleFilterChange}
        />
      ))}
    </div>
  );
};

// apps/web-vue/src/pages/saved/components/SavedFilter.vue
<script setup lang="ts">
import { useSavedStore } from '@/stores/saved-store';
import { storeToRefs } from 'pinia';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import AppRadioButton from '@/components/ui/AppRadioButton.vue';

const savedStore = useSavedStore();
const { currentFilter, shCount, ghCount, ihCount, bmcCount } =
  storeToRefs(savedStore);

const filters = computed(() => [
  { label: '전체', value: null, count: savedStore.totalCount },
  { label: 'SH', value: 'sh', count: shCount.value },
  { label: 'GH', value: 'gh', count: ghCount.value },
  { label: 'IH', value: 'ih', count: ihCount.value },
  { label: 'BMC', value: 'bmc', count: bmcCount.value },
]);

const setFilter = (filter: string | null) => {
  savedStore.setFilter(filter);
};

const isStuck = ref(false);
const filterContainer = ref<HTMLElement | null>(null);
let observer: IntersectionObserver | null = null;

onMounted(() => {
  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        isStuck.value = false;
      } else {
        isStuck.value = true;
      }
    },
    {
      rootMargin: '-1px 0px 0px 0px',
      threshold: 1,
    }
  );
  if (filterContainer.value) {
    observer.observe(filterContainer.value);
  }
});

onBeforeUnmount(() => {
  if (observer && filterContainer.value) {
    observer.unobserve(filterContainer.value);
  }
});

const stickyClass = computed(() => {
  return isStuck.value
    ? 'bg-white shadow-sm md:shadow-none md:bg-transparent'
    : 'bg-transparent';
});
</script>

<template>
  <div
    ref="filterContainer"
    class="sticky top-0 z-1 flex gap-2 overflow-x-auto px-4 py-2 transition-all md:relative"
    :class="stickyClass"
  >
    <AppRadioButton
      v-for="filter in filters"
      :key="filter.label"
      :label="filter.label"
      :value="filter.value"
      :count="filter.count"
      v-model="currentFilter"
      @update:modelValue="setFilter"
    />
  </div>
</template>
